include:
    # - path:
    #     - ./compose_files/ELK_stack.yml
    #     - ./compose_files/grafana_stack.yml
    #     - ./compose_files/security.yml
    #     - ./compose_files/web.yml
    #   project_directory: ..
    #   env_file:
    #     - ./envs/ELK_stack.env
    #     - ./envs/grafana_stack.env
    #     - ./envs/security.env
    #     - ./envs/web.env

  - path: ./compose_files/ELK_stack.yml
    # project_directory: ..
    env_file: ./envs/ELK_stack.env

  - path: ./compose_files/grafana_stack.yml
    # project_directory: ..
    env_file: ./envs/grafana_stack.env

  - path: ./compose_files/security.yml
    # project_directory: ..
    env_file: ./envs/security.env

  - path: ./compose_files/web.yml
    # project_directory: ..
    env_file: ./envs/web.env

networks:
  my_net:
    name: my_net
    driver: bridge
