FROM python:3.11-alpine3.19

RUN apk update \
    && apk add --no-cache \
    postgresql-client \
	postgresql-dev \ 
    gcc \            
    python3-dev \  
    musl-dev \      
    curl

WORKDIR /app

COPY utils ./utils

RUN pip install --upgrade pip

RUN pip install -r ./utils/requirements.txt

ENTRYPOINT ["/bin/sh", "./utils/setup_server.sh"]
